[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pimpmypfp = "8NKtq4YKTd5oeJxBX9rcZAwabBong4Cb9G1muHc86SGt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/shady/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
